apiVersion: apps/v1
kind: Deployment
metadata:
  name: piapi-deployment
  annotations:
    commitID: "9012cc72fbcf45b028d5af447e71a9d583de9feb"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: piapi
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 5
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: piapi
    spec:
      containers:
        - name: piapi
          image: 'xavelo/piapi:9012cc72fbcf45b028d5af447e71a9d583de9feb'
          ports:
            - containerPort: 80
#          resources:
#            requests:
#              cpu: 500m # Set CPU request to 250 millicpus (0.25 CPU)
#            limits:
#              cpu: 2000m
#          readinessProbe:
#            httpGet:
#              path: /actuator/health/readiness
#              port: 8080
#              initialDelaySeconds: 300
#              timeoutSeconds: 60
#              periodSeconds: 30
#          startupProbe:
#            httpGet:
#              path: /actuator/health/readiness
#              port: 8080
#            failureThreshold: 30
#            periodSeconds: 10
