apiVersion: apps/v1
kind: Deployment
metadata:
  name: piapi-deployment
  annotations:
    commitID: "91ac085b6b613239049f4847034b7dafdf117839"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: piapi
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: piapi
    spec:
      containers:
        - name: piapi
          image: 'xavelo/piapi:91ac085b6b613239049f4847034b7dafdf117839'
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 500m # Set CPU request to 250 millicpus (0.25 CPU)
            limits:
              cpu: 2000m
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
              initialDelaySeconds: 300
              timeoutSeconds: 60
              periodSeconds: 30
          startupProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            failureThreshold: 30
            periodSeconds: 10
