apiVersion: apps/v1
kind: Deployment
metadata:
  name: piapi-deployment
  annotations:
    commitID: "a964dbd6bb16c13b404c24269e40de15605fb63a"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: piapi
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: piapi
    spec:
      containers:
        - name: piapi
          image: 'xavelo/piapi:a964dbd6bb16c13b404c24269e40de15605fb63a'
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 500m # Set CPU request to 250 millicpus (0.25 CPU)
            limits:
              cpu: 2000m
#          readinessProbe:
#            httpGet:
#              path: /actuator/health/readiness
#              port: 8080
#              initialDelaySeconds: 300
#              timeoutSeconds: 60
#              periodSeconds: 30
