apiVersion: apps/v1
kind: Deployment
metadata:
  name: piapi-deployment
  annotations:
    commitID: "5d31dd97e4fe3550539762c95bdf2a6d2cav561"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: piapi
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: piapi
    spec:
      containers:
        - name: piapi
          image: 'xavelo/piapi:latest'
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 500m # Set CPU request to 250 millicpus (0.25 CPU)
            limits:
              cpu: 2000m
#          readinessProbe:
#            httpGet:
#              path: /actuator/health/readiness
#              port: 8080
#              initialDelaySeconds: 300
#              timeoutSeconds: 60
#              periodSeconds: 30