apiVersion: apps/v1
kind: Deployment
metadata:
  name: piapi-deployment
  annotations:
    commitID: "69d791dd128abde92d71712d60e3fa9e1ba12708"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: piapi
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: piapi
    spec:
      containers:
        - name: piapi
          image: 'xavelo/piapi:69d791dd128abde92d71712d60e3fa9e1ba12708'
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 500m # Set CPU request to 250 millicpus (0.25 CPU)
            limits:
              cpu: 2000m
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
              initialDelaySeconds: 300
              timeoutSeconds: 60
              periodSeconds: 30
          startupProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            failureThreshold: 30
            periodSeconds: 10
